[package]
name = "rate-limiter"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = "0.23.0"
lambda_runtime = "0.3.0"
serde_json = "1.0"
pyo3 = { version = "0.15.1", features = ["extension-module"] }